name: Deploy master or staging to GitHub Pages

on:
  push:
    branches:
      - master
      - staging

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # checkout current branch
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Initialise repo
        run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}

      - name: Run deploy script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git remote set-url origin "https://fregante:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          npm run deploy
