name: Run tests

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # checkout current branch
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Initialise repo
        run: yarn install

      - name: Run test scripts
        run: npm run test
